name: Build & Deploy Prisma to Dev

on:
  push:
    branches: [main]

jobs:
  build-push-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@dev-sam17"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npm run generate

      - name: Push schema to Dev MongoDB
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build TypeScript package
        run: npm run build

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
